name: Django test project

on: 
  push:
    branches: [new ]

jobs:
  testing:
    runs-on: ubuntu-latest
    env:
      PG_NAME: ${{ secrets.PG_NAME }}
      PG_USER: ${{ secrets.PG_USER }}
      PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
      PG_HOST: ${{ secrets.PG_HOST }}
      PG_PORT: ${{ secrets.PG_PORT }}
    services:
      postgres_main:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ env.PG_USER }}
          POSTGRES_PASSWORD: ${{ env.PG_PASSWORD }}
          POSTGRES_DB: ${{ env.PG_NAME }}
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Проверяем репозиторий на наличие изменений
      uses: actions/checkout@v2

    - name: Установка Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
      
    - name: Установка зависимостей
      run: pip install -r 1.5-ci-cd/work_with_database/requirements.txt
    
    - name: Линтинг кода
      run: flake8 --exclude 1.5-ci-cd/,2.4-celery/,1.2-deploy/
    
    - name: Тестирование
      run: python 1.5-ci-cd/work_with_database/manage.py test
      env:
        PG_NAME: ${{ env.PG_NAME }}
        PG_USER: ${{ env.PG_USER }}
        PG_PASSWORD: ${{ env.PG_PASSWORD }}
        PG_HOST: ${{ env.PG_HOST }}
        PG_PORT: ${{ env.PG_PORT }}
  # deploy:
  #   name: Доставка кода
  #   needs: testing
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Запуск скрипта обновления
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.SSH_HOST }}
  #         username: ${{ secrets.SSH_USERNAME }}
  #         password: ${{ secrets.SSH_PASSWORD }}
  #         script: expect /opt/cicd_test/deploy.exp
